bezier = smooth, 0.16, 1, 0.3, 1

animations {
    enabled = true

    animation = windows, 1, 3, smooth, popin 90%
    animation = windowsOut, 1, 3, smooth, popin 90%
    animation = border, 1, 6, smooth
    animation = fade, 1, 3, smooth
    animation = workspaces, 1, 3, smooth, slide
    animation = layers, 1, 2, smooth, slide
}
