[theme.templates]
builtin_ids = ["kitty", "starship", "gtk3", "gtk4", "btop"]

[theme.templates.user.fastfetch]
input_path  = "templates/fastfetch.jsonc"
output_path = "~/.config/fastfetch/config.jsonc"

[hooks]
colors_changed = "systemctl --user try-restart xdg-desktop-portal-gtk.service"

[widget.arch]
type = "launcher"
custom_image = "/usr/share/pixmaps/archlinux-logo.svg"
custom_image_colorize = true
