config_version = 14

[bar]
order = [ "default" ]

    [bar.default]
    border = "on_surface_variant"
    end = [ "media", "tray", "clipboard", "network", "bluetooth", "volume", "brightness", "battery", "session" ]
    margin_ends = 0
    margin_opposite_edge = 2
    radius = 50
    radius_top_left = 0
    radius_top_right = 0
    shadow = false
    start = [ "arch", "workspaces", "active_window", "widget" ]
    thickness = 38

[dock]
enabled = true
icon_size = 30
pinned = [ "google-chrome", "org.gnome.Nautilus", "code", "filezilla", "anydesk", "discord" ]
reserve_space = false
smart_auto_hide = true

[lockscreen]
blurred_desktop = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-clock@DP-5",
    "lockscreen-volume@DP-5",
    "lockscreen-sysmon@DP-5",
    "lockscreen-viz@DP-5",
    "lockscreen-label@DP-5",
    "lockscreen-login-box@DP-5",
    "lockscreen-login-box@DP-3",
    "lockscreen-login-box@eDP-1"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-clock@DP-5"]
    box_height = 220.0
    box_width = 560.0
    cx = 960.0
    cy = 300.0
    output = "DP-5"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

    [lockscreen_widgets.widget."lockscreen-label@DP-5"]
    box_height = 44.0
    box_width = 400.0
    cx = 960.0
    cy = 120.0
    output = "DP-5"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "label"

    [lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-3"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-5"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-5"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-5".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 906.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 14.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-sysmon@DP-5"]
    box_height = 100.0
    box_width = 240.0
    cx = 1090.0
    cy = 470.0
    output = "DP-5"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "system_monitor"

    [lockscreen_widgets.widget."lockscreen-viz@DP-5"]
    box_height = 150.0
    box_width = 720.0
    cx = 960.0
    cy = 740.0
    output = "DP-5"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "fancy_audio_visualizer"

    [lockscreen_widgets.widget."lockscreen-volume@DP-5"]
    box_height = 100.0
    box_width = 240.0
    cx = 830.0
    cy = 470.0
    output = "DP-5"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "volume"

[plugins]
enabled = [ "yuuto/arch-updater" ]

[shell]
lang = "fr"

    [shell.panel]
    launcher_placement = "attached"

[theme]
builtin = "Nord"
community_palette = "Neon Surf"
shell_mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4", "kitty" ]

[wallpaper]
directory = "__HOME__/Images/Wallpapers"

    [wallpaper.default]
    path = "__HOME__/Images/Wallpapers/wallhaven-391k7d.jpg"

    [wallpaper.last]
    path = "__HOME__/Images/Wallpapers/wallhaven-391k7d.jpg"

    [wallpaper.monitors.DP-3]
    path = "__HOME__/Images/Wallpapers/wallhaven-391k7d.jpg"

    [wallpaper.monitors.DP-5]
    path = "__HOME__/Images/Wallpapers/wallhaven-391k7d.jpg"

    [wallpaper.monitors.eDP-1]
    path = "__HOME__/Images/Wallpapers/wallhaven-391k7d.jpg"

[widget.taskbar]
item_spacing = 15

[widget.widget]
type = "yuuto/arch-updater:widget"