config_version = 14

[bar]
order = [ "default" ]

    [bar.default]
    border = "on_surface_variant"
    center = [ "control-center", "clock" ]
    end = [ "media", "tray", "clipboard", "network", "bluetooth", "volume", "brightness", "battery", "session" ]
    margin_ends = 0
    radius = 80
    radius_top_left = 0
    radius_top_right = 0
    scale = 1.0500000081956387
    shadow = false
    start = [ "arch", "workspaces", "active_window", "widget" ]
    thickness = 40

[control_center]
sidebar = "full"

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001", "desktop-widget-0000000000000003", "desktop-widget-0000000000000004" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 240.0
    box_width = 256.0
    cx = 1776.0
    cy = 244.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        clock_style = "analog"

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 0.0
    box_width = 0.0
    cx = 192.0
    cy = 982.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "media_player"

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    box_height = 0.0
    box_width = 0.0
    cx = 1792.0
    cy = 982.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000004.settings]
        stat = "cpu_usage"
        stat2 = "cpu_temp"

[dock]
enabled = true
cross_axis_padding = 4
item_spacing = 4
main_axis_padding = 8
icon_size = 30
margin_edge = 10
pinned = [ "google-chrome", "org.gnome.Nautilus", "code", "filezilla", "anydesk", "discord" ]
reserve_space = false
smart_auto_hide = true

[location]
auto_locate = true

[lockscreen]
enabled = false
monitors = [ "eDP-1" ]

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-3", "lockscreen-login-box@DP-5", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 24
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 1001.0
    output = "DP-3"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-5"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 969.0
    output = "DP-5"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-5".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 576.0
    cx = 960.0
    cy = 599.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.0
        background_radius = 15.0
        center_password_text = true
        input_opacity = 0.80000000000000004
        input_radius = 32.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = false
        show_media = true
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = true

[plugins]
enabled = []

[shell]
lang = "fr"

    [shell.panel]
    launcher_placement = "attached"

[theme]
builtin = "Nord"
community_palette = "Neon Surf"
pure_black_dark = false
shell_mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4", "hyprland", "kitty" ]
    community_ids = [ "vscode" ]

[wallpaper]
directory = "__HOME__/Images/Wallpapers"

    [wallpaper.default]
    path = "__HOME__/Images/Wallpapers/wallhaven-391k7d.jpg"

    [wallpaper.last]
    path = "__HOME__/Images/Wallpapers/wallhaven-391k7d.jpg"

    [wallpaper.monitors.DP-3]
    path = "__HOME__/Images/Wallpapers/wallhaven-391k7d.jpg"

    [wallpaper.monitors.DP-5]
    path = "__HOME__/Images/Wallpapers/wallhaven-391k7d.jpg"

    [wallpaper.monitors.eDP-1]
    path = "__HOME__/Images/Wallpapers/wallhaven-391k7d.jpg"

[widget.bluetooth]
show_label = true

[widget.taskbar]
item_spacing = 15

[widget.widget]
type = "yuuto/arch-updater:widget"