source = ~/.config/hypr/colors.conf

background {
    path = screenshot
    color = $bg
    blur_passes = 3
    blur_size = 8
}

image {
    path = ~/.config/hypr/avatar.png
    size = 220
    rounding = -1
    border_size = 3
    border_color = $accent
    position = 0, 310
    halign = center
    valign = center
}

input-field {
    size = 260, 60
    outline_thickness = 2
    dots_size = 0.25
    outer_color = $accent
    inner_color = $bg_alt
    font_color = $fg
    fade_on_empty = false
    placeholder_text = Password...
    position = 0, -60
    halign = center
    valign = center
}

label {
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = $fg
    font_size = 64
    font_family = Adwaita Sans
    position = 0, 90
    halign = center
    valign = center
}

label {
    text = cmd[update:60000] echo "$(date +'%A %d %B')"
    color = $fg_dim
    font_size = 16
    font_family = Adwaita Sans
    position = 0, 30
    halign = center
    valign = center
}

label {
    text = cmd[update:999999999] shuf -n1 ~/.config/hypr/dev-quotes.txt
    color = $fg_dim
    font_size = 13
    font_family = Adwaita Sans
    position = 0, -160
    halign = center
    valign = center
}
