[Appearance]
style=Fusion
custom_palette=true
color_scheme_path=~/.config/qt5ct/colors/current.conf
icon_theme=Tela

[Fonts]
general="Sans,10,-1,5,50,0,0,0,0,0"
fixed="FiraCode Nerd Font,10,-1,5,50,0,0,0,0,0"
