--ozone-platform-hint=wayland
# Pas de --gtk-version=4 : cassait le rendu des icones dans VS Code.
--ignore-gpu-blocklist
--enable-features=TouchpadOverscrollHistoryNavigation
--enable-wayland-ime
--password-store=gnome-libsecret
