#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/common.sh"

log_step "Post-install"

# La config end-4 est en Lua : nwg-displays ecrit monitors.lua / workspaces.lua,
# pas les .conf hyprlang d'avant. On seme monitors.lua s'il manque, sinon
# Hyprland demarre sans disposition d'ecrans definie.
if [[ ! -f "$HOME/.config/hypr/monitors.lua" ]]; then
    log_info "Seeding ~/.config/hypr/monitors.lua (edit with nwg-displays)"
    run mkdir -p "$HOME/.config/hypr"
    if [[ "$DRY_RUN" != "1" ]]; then
        printf '%s\n' \
            '-- Machine-local, non versionne. Reecrit par nwg-displays.' \
            'hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })' \
            > "$HOME/.config/hypr/monitors.lua"
    fi
fi

# Hyprland regenere un hyprland.conf bidon des qu'il n'en trouve pas, et ce
# stub prend le pas sur hyprland.lua qu'utilise end-4.
if [[ -f "$HOME/.config/hypr/hyprland.conf" ]] \
   && grep -q "autogenerated" "$HOME/.config/hypr/hyprland.conf" 2>/dev/null; then
    log_info "Removing Hyprland's autogenerated hyprland.conf stub (end-4 uses hyprland.lua)"
    run rm -f "$HOME/.config/hypr/hyprland.conf"
fi

run fc-cache -f

# --keep-zshrc est indispensable : sans lui KEEP_ZSHRC vaut "no" et
# l'installeur remplace ~/.zshrc par son propre modele. A ce stade c'est
# deja un lien stow, il serait donc casse et le prompt starship perdu.
if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
    log_info "Installing Oh My Zsh"
    run sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) \"\" --unattended --keep-zshrc"
fi

if [[ "$SHELL" != */zsh ]]; then
    log_info "Setting zsh as the default shell"
    run chsh -s "$(command -v zsh)" "$USER"
fi

# Spicetify patche le client Spotify dans /opt/spotify, qui appartient a
# root. On prend possession du dossier plutot que le chmod a+wr conseille
# par la doc : inscriptible par le seul utilisateur suffit, et evite un
# dossier inscriptible par tout le monde.
if command -v spicetify >/dev/null 2>&1 && [[ -d /opt/spotify ]]; then
    if [[ ! -w /opt/spotify ]]; then
        log_info "Taking ownership of /opt/spotify for spicetify"
        run sudo chown -R "$USER":"$USER" /opt/spotify
    fi
    log_info "Applying the graphite Spicetify theme"
    run spicetify config current_theme graphite color_scheme graphite
    run spicetify backup apply
    log_warn "Re-run 'spicetify apply' after each Spotify update: the patch is undone by it."
fi

# Reprend les etapes systeme de end-4 (sdata/subcmd-install/2.setups.sh) :
# ydotool pour la saisie virtuelle, i2c-dev pour la luminosite par DDC.
if ! id -nG "$USER" | grep -qwE "video"; then
    log_info "Adding $USER to video, input and i2c groups"
    run sudo groupadd -f i2c
    run sudo usermod -aG video,input,i2c "$USER"
    log_warn "Log out and back in for the new group membership to take effect."
fi

if [[ ! -f /etc/modules-load.d/uinput.conf ]]; then
    log_info "Enabling uinput and i2c-dev modules (ydotool, DDC brightness)"
    run sudo tee /etc/modules-load.d/uinput.conf <<< "uinput"
    run sudo tee /etc/modules-load.d/i2c-dev.conf <<< "i2c-dev"
    run sudo tee /etc/udev/rules.d/99-uinput.rules \
        <<< 'SUBSYSTEM=="misc", KERNEL=="uinput", MODE="0660", GROUP="input"'
fi

if ! systemctl --user is-enabled ydotool >/dev/null 2>&1; then
    log_info "Enabling the ydotool user service"
    run systemctl --user enable --now ydotool
fi

cat <<'EOF'

==================================================================
 Config end-4 (dots-hyprland) en graphite, installee.

 - Deconnecte-toi puis reconnecte-toi : Hyprland lit hyprland.lua,
   pas hyprland.conf, et les nouveaux groupes ne s'appliquent qu'a
   l'ouverture de session.
 - Le shell (barre, notifications, launcher) est quickshell -c ii,
   lance par la config Hyprland elle-meme.
 - Reglages : clic sur la barre, ou SUPER + I.
 - Palette : schema Material You "monochrome" + sombre force, defini
   dans quickshell/ii/modules/common/Config.qml.
==================================================================
EOF
