#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
source "$SCRIPT_DIR/lib/common.sh"

log_step "Post-install"

if [[ ! -f "$HOME/.config/hypr/monitors.lua" ]]; then
    log_info "Seeding ~/.config/hypr/monitors.lua (edit with nwg-displays)"
    run mkdir -p "$HOME/.config/hypr"
    if [[ "$DRY_RUN" != "1" ]]; then
        printf '%s\n' \
            '-- Machine-local, non versionne. Reecrit par nwg-displays.' \
            'hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })' \
            > "$HOME/.config/hypr/monitors.lua"
    fi
fi

if [[ -f "$HOME/.config/hypr/hyprland.conf" ]] \
   && grep -q "autogenerated" "$HOME/.config/hypr/hyprland.conf" 2>/dev/null; then
    log_info "Removing Hyprland's autogenerated hyprland.conf stub (end-4 uses hyprland.lua)"
    run rm -f "$HOME/.config/hypr/hyprland.conf"
fi

if [[ ! -f "$HOME/.config/kdeglobals" ]]; then
    log_info "Seeding ~/.config/kdeglobals from end-4's base"
    run mkdir -p "$HOME/.config"
    run cp "$REPO_DIR/vendor/end4/kdeglobals.default" "$HOME/.config/kdeglobals"
fi

run fc-cache -f

if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
    log_info "Installing Oh My Zsh"
    run sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) \"\" --unattended --keep-zshrc"
fi

if [[ "$SHELL" != */zsh ]]; then
    log_info "Setting zsh as the default shell"
    run chsh -s "$(command -v zsh)" "$USER"
fi

if command -v spicetify >/dev/null 2>&1 && [[ -d /opt/spotify ]]; then
    if [[ ! -w /opt/spotify ]]; then
        log_info "Taking ownership of /opt/spotify for spicetify"
        run sudo chown -R "$USER":"$USER" /opt/spotify
    fi
    log_info "Applying the graphite Spicetify theme"
    run spicetify config current_theme graphite color_scheme graphite
    run spicetify backup apply
    log_warn "Re-run 'spicetify apply' after each Spotify update: the patch is undone by it."
fi

KITTY_GENERATED_THEME="${XDG_STATE_HOME:-$HOME/.local/state}/quickshell/user/generated/terminal/kitty-theme.conf"
if [[ ! -f "$KITTY_GENERATED_THEME" ]]; then
    log_info "Seeding the generated kitty palette from the graphite theme"
    run mkdir -p "$(dirname "$KITTY_GENERATED_THEME")"
    run cp "$REPO_DIR/config/kitty/.config/kitty/theme.conf" "$KITTY_GENERATED_THEME"
fi

ILLOGICAL_VENV="${XDG_STATE_HOME:-$HOME/.local/state}/quickshell/.venv"
if [[ ! -x "$ILLOGICAL_VENV/bin/kde-material-you-colors" ]]; then
    if command -v uv >/dev/null 2>&1; then
        log_info "Creating the illogical-impulse Python venv"
        run mkdir -p "$ILLOGICAL_VENV"
        run uv venv --prompt .venv "$ILLOGICAL_VENV" -p 3.12
        run uv pip install --python "$ILLOGICAL_VENV/bin/python" \
            -r "$REPO_DIR/vendor/end4/requirements.txt"
    else
        log_warn "uv not found; skipping the Python venv (Qt/KDE apps will not follow the palette)."
    fi
fi

if ! id -nG "$USER" | grep -qwE "video"; then
    log_info "Adding $USER to video, input and i2c groups"
    run sudo groupadd -f i2c
    run sudo usermod -aG video,input,i2c "$USER"
    log_warn "Log out and back in for the new group membership to take effect."
fi

if [[ ! -f /etc/modules-load.d/uinput.conf ]]; then
    log_info "Enabling uinput and i2c-dev modules (ydotool, DDC brightness)"
    run sudo tee /etc/modules-load.d/uinput.conf <<< "uinput"
    run sudo tee /etc/modules-load.d/i2c-dev.conf <<< "i2c-dev"
    run sudo tee /etc/udev/rules.d/99-uinput.rules \
        <<< 'SUBSYSTEM=="misc", KERNEL=="uinput", MODE="0660", GROUP="input"'
fi

if ! systemctl --user is-enabled ydotool >/dev/null 2>&1; then
    log_info "Enabling the ydotool user service"
    run systemctl --user enable --now ydotool
fi

cat <<'EOF'

==================================================================
 Config end-4 (dots-hyprland) en graphite, installee.

 - Deconnecte-toi puis reconnecte-toi : Hyprland lit hyprland.lua,
   pas hyprland.conf, et les nouveaux groupes ne s'appliquent qu'a
   l'ouverture de session.
 - Le shell (barre, notifications, launcher) est quickshell -c ii,
   lance par la config Hyprland elle-meme.
 - Reglages : clic sur la barre, ou SUPER + I.
 - Palette : schema Material You "monochrome" + sombre force, defini
   dans quickshell/ii/modules/common/Config.qml.
==================================================================
EOF
